{{- if .Values.dcgmExporter.config }}
{{- if .Values.dcgmExporter.config.create}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dcgmExporter.config.name | default "dcgm-exporter-config"}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gpu-operator.labels" . | nindent 4 }}
data:
  dcgm-metrics.csv: |
  {{- if .Values.dcgmExporter.config.data }}
{{ .Values.dcgmExporter.config.data | nindent 4 }}
  {{- else }}
{{ .Files.Get "custom/dcgm-exporter/dcgm-metrics.csv" | indent 4 }}
  {{- end }}
{{- end }}